function state = initialize_system(params)
    % Constants
    alpha = 0.05;
    beta = 0.1;
    gamma = 0.02;

    dt = 1;
    time = 0:dt:params.sim_time;

    T = zeros(1, length(time));
    FanSpeed = strings(1, length(time));
    Status = strings(1, length(time));

    T(1) = params.T0;

    state = struct( ...
        'T', T, ...
        'FanSpeed', FanSpeed, ...
        'Status', Status, ...
        'time', time, ...
        'dt', dt, ...
        'alpha', alpha, ...
        'beta', beta, ...
        'gamma', gamma ...
    );
end
